### ISSUE TITLE
Wrong link in readme for @wemake-services/stylelint-config-strict-scss

### ISSUE THREAD

**Issue by nikoladev** [wemake-services/wemake-frontend-styleguide#455]
On [this page](https://github.com/wemake-services/wemake-frontend-styleguide/tree/master/packages/stylelint-config-scss) it links to [the old repo](https://github.com/wemake-services/stylelint-config-strict-scss/blob/master/index.js) under "sensible defaults". It should probably link to [the current repo](https://github.com/wemake-services/wemake-frontend-styleguide/blob/master/packages/stylelint-config-scss/index.js).

Sorry for not opening up a PR, but I can't edit the readme directly from Github and at the moment I don't have the correct tools to clone the repo to properly fix it.

**Comment by sobolevn** [comment]
@nikoladev thanks a lot for letting me know! 

I will probably fix it later, but I would love to have your contribution counted! 
So, you are more than welcome to send the fix before I do it myself 🙂

**Comment by mfranzke** [comment]
@nikoladev this seems to have been fixed. Could you please check and close the ticket?

**Comment by sobolevn** [comment]
Thanks!
